name: zhyluu_ui
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  go_router: ^11.1.4
  flutter_hooks: ^0.20.3
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  expandable_page_view: ^1.0.17
  url_launcher: ^6.1.14
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  excel: ^3.0.0
  intl: ^0.18.0

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/data/

    - assets/icons/
    - assets/icons/main/
    - assets/icons/main/app_bar/inverted/
    - assets/icons/main/app_bar/light/
    - assets/icons/main/app_bar/regular/
    - assets/icons/main/drawer/
    - assets/icons/appartment/
    - assets/icons/where_to_insulate/
    - assets/icons/house/

    - assets/images/
    - assets/images/about/
    - assets/images/starting/
    - assets/images/main/
    - assets/images/appartment/
    - assets/images/door/
    - assets/images/where_to_insulate/
    - assets/images/how_to_insulate/
    - assets/images/how_to_insulate/pros_and_cons/
    - assets/images/fundament/
    - assets/images/roof/
    - assets/images/wall/
    - assets/images/floor/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 16